### ISSUE TITLE
MakeFieldsFinal is marking some stuff final that shouldn't be

### ISSUE THREAD

**Issue by champgm** [champgm/IntelliJCodeGenerationPlugin#21]
There is an annotation in Mockito, "@Mock" Which denotes that a variable is a mocked class and somehow instantiates it. The plugin/action doesn't see or recognize that instantiation and marks the field as final.

**Comment by sjdurfey** [comment]
using reflections you can pull the annotation off the member variables for the class. i guess you could do that and check for that specific annotation as a hack?

**Comment by champgm** [comment]
https://github.com/champgm/IntelliJCodeGenerationPlugin/pull/23
